# generate a docker compose file that will run a webserver and serve the static files (current directory)
version: '3'
services:
  web:
    image: nginx
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - 8000:80
